spring:
    datasource:
        url: jdbc:mysql://localhost:3306/RATHNA?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: developer
        password: dev@MSQL25
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: false
                dialect: org.hibernate.dialect.MySQLDialect

jwt:
    secret: RathnaProductsSecretKeyForJWTTokenGeneration2024MustBe256BitsLong
    expiration: 86400000

server:
    port: 8080
    address: 0.0.0.0 # Allow external access for server deployment
